apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2023-08-18T15:29:09Z"
  name: cicd
  namespace: default
  resourceVersion: "9973"
  uid: ed2e6595-4737-4715-9051-9d35ef9a5500
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cicd
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gitlab
