apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: my-sql-root-password
          volumeMounts:
            - name: mysql-presistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-presistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
