apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: weather-ui-svc
  name: weather-ui-svc
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: weather-ui
  type: ClusterIP
status:
  loadBalancer: {}
