apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weather-ui
  name: weather-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather-ui
    spec:
      containers:
      - image: imadelbouhati/weatherapp-ui:1.3.0
        name: weatherapp-ui
        resources: {}
        env:
          - name: AUTH_HOST
            valueFrom:
              configMapKeyRef:
                name: config-ui
                key: auth_host
          - name: AUTH_PORT
            valueFrom:
              configMapKeyRef:
                name: config-ui
                key: auth_port
          - name: WEATHER_HOST
            valueFrom:
              configMapKeyRef:
                name: config-ui
                key: weather_host
          - name: WEATHER_PORT
            valueFrom:
              configMapKeyRef:
                name: config-ui
                key: weather_port
status: {}
