apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-weather
  name: weather-weather
spec:
  ports:
    - name: weather-weather
      port: 5000
      protocol: TCP
      targetPort: 5000
  type: ClusterIP
  selector:
    app: weather-weather

       
