apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-weather
  name: weather-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-weather
  template:
    metadata:
      labels:
        app: weather-weather
    spec:
      containers:
      - image: imadelbouhati/weatherapp-weather:1.3.0
        name: weatherapp-weather
        ports:
          - name: weather-weather
            containerPort: 5000
            protocol: TCP
        env:
          - name: APIKEY
            valueFrom: 
              secretKeyRef: 
                name: api-key-secret
                key: api-key

 